[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
[context.deploy-preview.environment]
  KONTENT_PROJECT_ID="22c0ab58-ad73-00a9-80aa-1b3a8815223d"
  KONTENT_PREVIEW_API_KEY="ew0KICAiYWxnIjogIkhTMjU2IiwNCiAgInR5cCI6ICJKV1QiDQp9.ew0KICAianRpIjogIjc1MjAzY2YzYmRmYzQ4Njc4ZmU1YjQwODYzYmI5MzFkIiwNCiAgImlhdCI6ICIxNjMxMTEzMjQ3IiwNCiAgImV4cCI6ICIxOTc2NzEzMjQ3IiwNCiAgInByb2plY3RfaWQiOiAiMjJjMGFiNThhZDczMDBhOTgwYWExYjNhODgxNTIyM2QiLA0KICAidmVyIjogIjEuMC4wIiwNCiAgImF1ZCI6ICJwcmV2aWV3LmRlbGl2ZXIua2VudGljb2Nsb3VkLmNvbSINCn0.wky-EkVYqqaSosyDB3IRf5GLNcoCS5HnTGus6j4RuU0"
  PREVIEW_SECRET=""
